# for resources image 

resources:
  - name: imgs
    type: image
    imageName: drydock/u16phpall #shippabledocker/u16phpall
    configuration:
      integrationName: dockerInt
    version:
      imageTag: test5.6
 
      
pipelines:
  - name: pipeline
    steps:
      - name: s1
        type: bash
#         triggeredBy:
#         requires:
#           resources:
#             - imgs
        execution:
          onExecute:
            - printenv
            - write_output imgs imageTag=$STEP_ID
        outputResources:
          - imgs

      - name: s2
        type: bash
        requires:
          resources:
            - imgs
        execution:
          onExecute:
            - echo $res_imgs_imageTag 
        
#       - name: s3
#         type: bash
#         requires:
#           resources:
#             - imgs
#         execution:
#           onExecute:
#             - echo $res_imgs_imageTag 
        
        
 
