# for resources image 

resources:
  - name: imgs
    type: image
    imageName: shippabledocker/u16phpall
    configuration:
      integrationName: dockerInt
    initialVersion:
      imageTag: test5.6
 
      
pipelines:
  - name: pipeline
    steps:
      - name: s1
        type: bash
        execution:
          onExecute:
            - printenv
            - write_output imgs imageTag=$STEP_ID
        outputResources:
          - imgs

      - name: s2
        type: bash
        requires:
          resources:
            - imgs
        execution:
          onExecute:
            - echo $res_imgs_imageTag 
        
        
